Partly fixed (READ DESC)
I have fixed most the problem of undefined X and M.

Now you fix this problem:
  File "/Users/akshat/Documents/GitHub/PythonPrograms/Matrix.py", line 73, in <module>
    BasicOps()
  File "/Users/akshat/Documents/GitHub/PythonPrograms/Matrix.py", line 37, in BasicOps
    result = Math.linalg.solve(M + X)
  File "<__array_function__ internals>", line 4, in solve
TypeError: _solve_dispatcher() missing 1 required positional argument: 'b'